// Seed script — populates the database with sample provenance records
// Run via: POST /api/v1/seed
import { createRecord } from "./provenance.server";

const SAMPLE_RECORDS = [
  {
    source_project: "gummy-bear" as const,
    source_project_id: "constellation-proj-001",
    user_id: "demo-user",
    brief: "Build a task management app with team workspaces, real-time task sync, user authentication with JWT, Stripe billing for premium tiers, and a dashboard with analytics charts.",
    tech_stack: "React + Next.js + Node.js/Express + PostgreSQL + Stripe",
    version_number: 3,
    file_count: 18,
    total_lines: 2840,
    commit_hash: "a1b2c3d4e5f6",
    commit_message: "Initial commit — generated by Constellation Engine",
    repo_url: "https://github.com/Grantgazvoda-alt/bitfordge",
    repo_name: "Grantgazvoda-alt/bitfordge",
    pipeline_duration_ms: 145000,
    model_used: "gpt-4o",
    fix_rounds: 1,
    build_status: "passed" as const,
    test_status: "passed" as const,
    lineage: [
      { agent_id: "architect", reasoning: "Chose Next.js for SSR + React component model. Express for REST API. PostgreSQL for relational data. Stripe for billing.", model_used: "gpt-4o", duration_ms: 15000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "frontend", file_path: "frontend/src/app/dashboard/page.tsx", file_language: "typescript", reasoning: "Built dashboard with analytics charts using Recharts. Team workspace selector in sidebar.", model_used: "gpt-4o", content_hash: "sha256-a1b2c3d4e5f6", duration_ms: 35000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "frontend", file_path: "frontend/src/components/task-board.tsx", file_language: "typescript", reasoning: "Drag-and-drop task board with real-time sync via WebSocket.", model_used: "gpt-4o", content_hash: "sha256-b2c3d4e5f6a7", duration_ms: 28000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "backend", file_path: "backend/src/routes/tasks.ts", file_language: "typescript", reasoning: "CRUD API for tasks with WebSocket updates. JWT middleware for auth.", model_used: "gpt-4o", content_hash: "sha256-c3d4e5f6a7b8", duration_ms: 22000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "backend", file_path: "backend/src/routes/auth.ts", file_language: "typescript", reasoning: "JWT login/register with refresh tokens. Password hashing with bcrypt.", model_used: "gpt-4o", content_hash: "sha256-d4e5f6a7b8c9", duration_ms: 18000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "database", file_path: "database/migrations/001_create_tables.sql", file_language: "sql", reasoning: "Users, workspaces, tasks, subscriptions tables with proper FK constraints.", model_used: "gpt-4o", content_hash: "sha256-e5f6a7b8c9d0", duration_ms: 12000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "api", file_path: "backend/src/routes/billing.ts", file_language: "typescript", reasoning: "Stripe checkout session creation, webhook handling, subscription management.", model_used: "gpt-4o", content_hash: "sha256-f6a7b8c9d0e1", duration_ms: 20000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "devops", file_path: "docker/Dockerfile", file_language: "dockerfile", reasoning: "Multi-stage Docker build for frontend and backend. Nginx reverse proxy.", model_used: "gpt-4o", content_hash: "sha256-a7b8c9d0e1f2", duration_ms: 10000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "reviewer", reasoning: "All files reviewed. API routes match frontend calls. Database schema supports all queries. No integration issues found.", model_used: "gpt-4o", duration_ms: 8000, prompt_snapshot: "", retry_count: 0, error_message: "" },
    ],
  },
  {
    source_project: "stackforge" as const,
    source_project_id: "sf-proj-002",
    user_id: "demo-user",
    brief: "Build a REST API for a blog platform with user authentication, post CRUD, comments, and a search endpoint.",
    tech_stack: "FastAPI + MongoDB + JWT + Docker",
    version_number: 1,
    file_count: 8,
    total_lines: 1200,
    pipeline_duration_ms: 89000,
    model_used: "gpt-4o-mini",
    fix_rounds: 0,
    build_status: "passed" as const,
    test_status: "not_run" as const,
    lineage: [
      { agent_id: "architect", reasoning: "Chose FastAPI for async Python backend. MongoDB for flexible document storage.", model_used: "gpt-4o", duration_ms: 12000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "backend", file_path: "backend/src/main.py", file_language: "python", reasoning: "FastAPI app with CORS, rate limiting, and error handlers.", model_used: "gpt-4o-mini", content_hash: "sha256-b8c9d0e1f2a3", duration_ms: 20000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "database", file_path: "database/schema.py", file_language: "python", reasoning: "MongoDB models for User, Post, Comment with indexes.", model_used: "gpt-4o-mini", content_hash: "sha256-c9d0e1f2a3b4", duration_ms: 15000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "api", file_path: "backend/src/routes/posts.py", file_language: "python", reasoning: "CRUD endpoints for posts with search filtering and pagination.", model_used: "gpt-4o-mini", content_hash: "sha256-d0e1f2a3b4c5", duration_ms: 18000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "devops", file_path: "docker/Dockerfile", file_language: "dockerfile", reasoning: "Multi-stage Docker build for Python FastAPI app.", model_used: "gpt-4o-mini", content_hash: "sha256-e1f2a3b4c5d6", duration_ms: 8000, prompt_snapshot: "", retry_count: 0, error_message: "" },
    ],
  },
  {
    source_project: "gummy-bear" as const,
    source_project_id: "constellation-proj-003",
    user_id: "demo-user",
    brief: "Build a landing page for a SaaS product with hero section, feature grid, pricing table, and contact form.",
    tech_stack: "React + Tailwind CSS + Vite",
    version_number: 2,
    file_count: 6,
    total_lines: 890,
    pipeline_duration_ms: 62000,
    model_used: "gpt-4o",
    fix_rounds: 2,
    build_status: "passed" as const,
    test_status: "failed" as const,
    lineage: [
      { agent_id: "architect", reasoning: "Static React site with Tailwind for styling. No backend needed.", model_used: "gpt-4o", duration_ms: 10000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "frontend", file_path: "frontend/src/pages/Home.tsx", file_language: "typescript", reasoning: "Hero with animated gradient background. Feature grid with hover effects.", model_used: "gpt-4o", content_hash: "sha256-f2a3b4c5d6e7", duration_ms: 25000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "frontend", file_path: "frontend/src/components/PricingTable.tsx", file_language: "typescript", reasoning: "Three-tier pricing table with monthly/annual toggle. Stripe checkout links.", model_used: "gpt-4o", content_hash: "sha256-a3b4c5d6e7f8", duration_ms: 18000, prompt_snapshot: "", retry_count: 0, error_message: "" },
      { agent_id: "devops", file_path: "Dockerfile", file_language: "dockerfile", reasoning: "Nginx static file server for production build.", model_used: "gpt-4o", content_hash: "sha256-b4c5d6e7f8a9", duration_ms: 5000, prompt_snapshot: "", retry_count: 0, error_message: "" },
    ],
  },
];

export async function seedDatabase(): Promise<{ created: number; errors: string[] }> {
  const errors: string[] = [];
  let created = 0;

  for (const record of SAMPLE_RECORDS) {
    try {
      await createRecord(record);
      created++;
    } catch (e) {
      errors.push(`Failed to create record for ${record.source_project_id}: ${e}`);
    }
  }

  return { created, errors };
}